from playwright.sync_api import sync_playwright
from pathlib import Path
import os
out=Path(__file__).resolve().parents[1]/'artifacts';out.mkdir(exist_ok=True)
base_url=os.environ.get('CWA_TEST_URL','http://127.0.0.1:8000')
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True)
 page=browser.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
 errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto(base_url,wait_until='networkidle',timeout=90000)
 page.wait_for_function("parseInt(document.getElementById('station-count').textContent,10)>0",timeout=30000)
 print('Stations:',page.locator('#station-count').inner_text())
 page.select_option('#county-select',label='臺北市')
 print('Taipei:',page.locator('#station-count').inner_text())
 page.fill('#search-input','不存在的測站')
 assert page.locator('#station-count').inner_text().startswith('0 /')
 page.fill('#search-input','')
 page.select_option('#county-select','ALL')
 page.click('[data-mode="heatmap"]')
 page.click('[data-mode="cluster"]')
 print('Cluster:',page.locator('.marker-cluster').count())
 page.click('[data-mode="markers"]')
 page.screenshot(path=str(out/'stations-desktop.png'),full_page=True)
 page.click('[data-view="forecast"]')
 page.wait_for_function("document.querySelectorAll('#forecast-table tr').length===7")
 assert page.locator('#daily-table tr').count()==6
 page.select_option('#forecast-region',label='東南部地區')
 print('Forecast:',page.locator('#chart-title').inner_text(),page.locator('#forecast-date option').count(),'days')
 with page.expect_download() as d:
  page.click('#forecast-export')
 download=d.value
 print('CSV:',download.suggested_filename)
 page.locator('#sidebar').evaluate('e => e.scrollTop=0')
 page.wait_for_timeout(400)
 page.screenshot(path=str(out/'forecast-desktop.png'),full_page=True)
 page.locator('summary').click()
 page.locator('#sql-input-query').fill('SELECT count(*) AS total FROM WeeklyForecasts')
 page.click('#btn-run-sql')
 page.wait_for_function("document.getElementById('sql-result-output').textContent.includes('42')")
 print('SQL passed')
 page.click('[data-view="stations"]')
 page.locator('#history-range').evaluate("e => {e.value='0';e.dispatchEvent(new Event('input'));}")
 page.wait_for_function("document.getElementById('map-message').textContent.includes('歷史快照')")
 page.click('#history-live')
 print('History passed')
 page.set_viewport_size({'width':390,'height':844})
 page.click('#toggle-sidebar-btn')
 page.wait_for_timeout(400)
 page.screenshot(path=str(out/'mobile-map.png'),full_page=True)
 page.click('#toggle-sidebar-btn')
 page.click('[data-view="forecast"]')
 page.wait_for_timeout(400)
 page.screenshot(path=str(out/'mobile-forecast.png'),full_page=True)
 assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
 print('JS errors:',errors)
 assert not errors
 browser.close()
